name: Build Extension

on:
  push:
    paths:
    - 'client/**'
  pull_request:
    branches:
    - main
    - development
    paths:  
    - 'client/**'

jobs:
  build_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.15'
          
      - name: Install dependencies
        run: npm ci

      - name: build for chrome
        run: npm run build

      - name: build for firefox
        run: npm run build:firefox